// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTlptiDZ1VxWKg0JW9Tcn08UWovz0UV40',
    appId: '1:392181011930:web:a5475dd84296ce495a9ce3',
    messagingSenderId: '392181011930',
    projectId: 'test-fc2cf',
    authDomain: 'test-fc2cf.firebaseapp.com',
    storageBucket: 'test-fc2cf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHL996hm-f_Yptr3FIuZSfqsdQJOeRq1M',
    appId: '1:392181011930:android:f09ef7c444c112915a9ce3',
    messagingSenderId: '392181011930',
    projectId: 'test-fc2cf',
    storageBucket: 'test-fc2cf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARaHfZRwscK-0yqbHpW7LJpr7fItaXf0g',
    appId: '1:392181011930:ios:c5b3638e0a537ec95a9ce3',
    messagingSenderId: '392181011930',
    projectId: 'test-fc2cf',
    storageBucket: 'test-fc2cf.appspot.com',
    iosBundleId: 'com.example.practiceFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARaHfZRwscK-0yqbHpW7LJpr7fItaXf0g',
    appId: '1:392181011930:ios:c5b3638e0a537ec95a9ce3',
    messagingSenderId: '392181011930',
    projectId: 'test-fc2cf',
    storageBucket: 'test-fc2cf.appspot.com',
    iosBundleId: 'com.example.practiceFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTlptiDZ1VxWKg0JW9Tcn08UWovz0UV40',
    appId: '1:392181011930:web:59f679303703a8e55a9ce3',
    messagingSenderId: '392181011930',
    projectId: 'test-fc2cf',
    authDomain: 'test-fc2cf.firebaseapp.com',
    storageBucket: 'test-fc2cf.appspot.com',
  );
}
